# Generated by Django 5.2.7 on 2025-10-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_cart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
