# Generated by Django 5.2.7 on 2025-10-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_cart_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
