# Generated by Django 5.2.7 on 2025-10-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_category_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
