# Generated by Django 5.2.7 on 2025-10-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_order_payment_method_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="banned_until",
        ),
    ]
